mode = "debug"
port = ":8000"

[debug]
    module = "" # 英文逗号间隔，可选值 mysql,http, + 自定义业务模块
    way = "stdout" # 可选值 log, stdout, 默认 stdout

[log]
    path = "./logs/log.log"
    closed = false
    max_size = 10240
    max_age = 7
    max_backup = 10
    custome_parameter = ["trace_id", "span_id", "parent_span_id", "span_kind", "span_name", "span_status", "span_start_time", "span_end_time", "span_duration", "user_id"]

[http]
    transparent_parameter = ["trace_id"]
    debug = false

[db]
    [db.main]
        driver = "mysql"
        dsn = [
            "root:@tcp(127.0.0.1:3306)/dbname?charset=utf8&parseTime=True&loc=Local",
        ]
        max_conn = 50           # 最大连接数
        max_idle_conn = 25      # 最大空闲连接数
        conn_max_life = 3600    # 连接最长持续时间， 默认1小时，单位秒
        is_log = true           # 是否记录日志  日志级别为info

[cache]
    [cache.main]
        driver =  "redis"
        node = [
            "127.0.0.1:6379"
        ]
        password = ""
        db = 0